/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ApplicationsRouteImport } from './routes/applications'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OrderingRouteImport } from './routes/ordering'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as SelectorRouteImport } from './routes/selector'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as AboutLeadershipRouteImport } from './routes/about.leadership'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ProductsIdRouteImport } from './routes/products/$id'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SupportCloningRouteImport } from './routes/support/cloning'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderingRoute = OrderingRouteImport.update({
  id: '/ordering',
  path: '/ordering',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectorRoute = SelectorRouteImport.update({
  id: '/selector',
  path: '/selector',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => AboutRoute,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JournalRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportCloningRoute = SupportCloningRouteImport.update({
  id: '/support/cloning',
  path: '/support/cloning',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/ordering': typeof OrderingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/selector': typeof SelectorRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/support/cloning': typeof SupportCloningRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/ordering': typeof OrderingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/selector': typeof SelectorRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/support/cloning': typeof SupportCloningRoute
  '/support': typeof SupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/account': typeof AccountRoute
  '/applications': typeof ApplicationsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRouteWithChildren
  '/ordering': typeof OrderingRoute
  '/privacy': typeof PrivacyRoute
  '/quality': typeof QualityRoute
  '/quote': typeof QuoteRoute
  '/returns': typeof ReturnsRoute
  '/selector': typeof SelectorRoute
  '/shipping': typeof ShippingRoute
  '/shop': typeof ShopRoute
  '/terms': typeof TermsRoute
  '/vendors': typeof VendorsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/products/$id': typeof ProductsIdRoute
  '/support/cloning': typeof SupportCloningRoute
  '/support/': typeof SupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/applications'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/journal'
    | '/ordering'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/returns'
    | '/selector'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/about/leadership'
    | '/journal/$slug'
    | '/products/$id'
    | '/support/cloning'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/applications'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/journal'
    | '/ordering'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/returns'
    | '/selector'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/about/leadership'
    | '/journal/$slug'
    | '/products/$id'
    | '/support/cloning'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/applications'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/journal'
    | '/ordering'
    | '/privacy'
    | '/quality'
    | '/quote'
    | '/returns'
    | '/selector'
    | '/shipping'
    | '/shop'
    | '/terms'
    | '/vendors'
    | '/about/leadership'
    | '/journal/$slug'
    | '/products/$id'
    | '/support/cloning'
    | '/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
  AccountRoute: typeof AccountRoute
  ApplicationsRoute: typeof ApplicationsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRouteWithChildren
  OrderingRoute: typeof OrderingRoute
  PrivacyRoute: typeof PrivacyRoute
  QualityRoute: typeof QualityRoute
  QuoteRoute: typeof QuoteRoute
  ReturnsRoute: typeof ReturnsRoute
  SelectorRoute: typeof SelectorRoute
  ShippingRoute: typeof ShippingRoute
  ShopRoute: typeof ShopRoute
  TermsRoute: typeof TermsRoute
  VendorsRoute: typeof VendorsRoute
  ProductsIdRoute: typeof ProductsIdRoute
  SupportCloningRoute: typeof SupportCloningRoute
  SupportIndexRoute: typeof SupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applications': {
      id: '/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordering': {
      id: '/ordering'
      path: '/ordering'
      fullPath: '/ordering'
      preLoaderRoute: typeof OrderingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selector': {
      id: '/selector'
      path: '/selector'
      fullPath: '/selector'
      preLoaderRoute: typeof SelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/leadership': {
      id: '/about/leadership'
      path: '/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof AboutRoute
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof JournalRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/cloning': {
      id: '/support/cloning'
      path: '/support/cloning'
      fullPath: '/support/cloning'
      preLoaderRoute: typeof SupportCloningRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AboutRouteChildren {
  AboutLeadershipRoute: typeof AboutLeadershipRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutLeadershipRoute: AboutLeadershipRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

interface JournalRouteChildren {
  JournalSlugRoute: typeof JournalSlugRoute
}

const JournalRouteChildren: JournalRouteChildren = {
  JournalSlugRoute: JournalSlugRoute,
}

const JournalRouteWithChildren =
  JournalRoute._addFileChildren(JournalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
  AccountRoute: AccountRoute,
  ApplicationsRoute: ApplicationsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRouteWithChildren,
  OrderingRoute: OrderingRoute,
  PrivacyRoute: PrivacyRoute,
  QualityRoute: QualityRoute,
  QuoteRoute: QuoteRoute,
  ReturnsRoute: ReturnsRoute,
  SelectorRoute: SelectorRoute,
  ShippingRoute: ShippingRoute,
  ShopRoute: ShopRoute,
  TermsRoute: TermsRoute,
  VendorsRoute: VendorsRoute,
  ProductsIdRoute: ProductsIdRoute,
  SupportCloningRoute: SupportCloningRoute,
  SupportIndexRoute: SupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
